### ISSUE TITLE
Allow changing models (multilingual support)

### ISSUE THREAD

**Issue by KeystoneScience** [FelixWaweru/elevenlabs-node#12]

**Comment by Diego-Schmidt** [comment]
I beleave you just need to add the model option In index.js , model='eleven_multilingual_v1' , for example in line 38 , after text: textInput,

**Comment by FelixWaweru** [comment]
> I beleave you just need to add the model option In index.js , model='eleven_multilingual_v1' , for example in line 38 , after text: textInput,

Good suggestion @Diego-Schmidt 
We can also look into adding this as a default feature in the next release.

**Comment by FelixWaweru** [comment]
This feature is now available in the package:
https://github.com/FelixWaweru/elevenlabs-node#features
