### ISSUE TITLE
Text to speech not waiting until the audio is created.

### ISSUE THREAD

**Issue by juanpecuelo** [FelixWaweru/elevenlabs-node#16]
Description of the problem
Currently, the textToSpeech function in its current implementation, returns a response before the audio file has been fully created. As a result, when attempting to read the audio file immediately after calling textToSpeech, the file might not exist yet, which can lead to errors.

Steps to reproduce
1. Call the textToSpeech function and save the response in a variable.
2. Immediately afterwards, try to read the audio file returned by textToSpeech.

Expected behavior
The `textToSpeech` function should return only after the audio file has been completely created and it can be accessed without any issues.

Possible solution
One could modify the `textToSpeech` function to return a promise that resolves only after the audio file has been completely created. Below is an example of how this solution could be implemented:

const textToSpeech = async (apiKey, voiceID, fileName, textInput, stability, similarityBoost, modelId) => {
  try {
    // ... existing code ...

    const writeStream = fs.createWriteStream(fileName);
    response.data.pipe(writeStream);

    return new Promise((resolve, reject) => {
      writeStream.on('finish', () => resolve(fileName));
      writeStream.on('error', reject);
    });

  } catch (error) {
    console.log(error);
  }
};

In this code, we create a new promise that resolves with the file name only after the writing of the file has been completed. This way, the textToSpeech function resolves only after the audio file has been fully created.

I hope this suggestion is useful and can be implemented to avoid issues when trying to access the audio file immediately after calling textToSpeech. I appreciate your attention and look forward to a prompt resolution.

**Comment by FelixWaweru** [comment]
Thank you for sharing this @juanpecuelo 

I'll test the possible solution out. In the meantime you can use `await` when calling the `textToSpeech` function to wait for the response

**Comment by genekogan** [comment]
I am having the same issue. Problem does not appear solved. 

```
await voice.textToSpeech(apiKey, voiceID, fileName, textInput);
// fileName does not exist yet
```

**Comment by FelixWaweru** [comment]
Thanks for sharing this @genekogan 
I've reopened the issue and will look into what is happening

**Comment by FelixWaweru** [comment]
Thanks for sharing this issue @juanpecuelo @genekogan 

This issue has been fixed in the latest release:
https://github.com/FelixWaweru/elevenlabs-node/releases/tag/elevenlabs-node%401.2.0
