### ISSUE TITLE
Text Size

### ISSUE THREAD

**Issue by ViniTamanhao** [FelixWaweru/elevenlabs-node#17]
Not quite sure if this is a issue or not, but when using the package for small amounts of text it works just fine, but when using it with larger samples it just errors...
To be fair I have myself got the same exact error when trying to use the API directly, but I'm not quite sure why this is happening. According to the API documentation, the max amount of characters should be 5000, but both your package and my direct use of the API error after around 500 characters

**Comment by FelixWaweru** [comment]
@ViniTamanhao it's possible that it could be an issue with the ElevenLabs API. Is the audio file showing up in your [history](https://beta.elevenlabs.io/history)?

**Comment by FelixWaweru** [comment]
This is occurring in the core ElevenLabs API
