### ISSUE TITLE
Passing from server to client

### ISSUE THREAD

**Issue by kelvin-zhao** [FelixWaweru/elevenlabs-node#18]
Hi, I'm trying to get the audio via a firebase function and passing it back to the client to play, but I can't seem to get it to work, how can I make it something I am able to pass by to the client?

**Comment by FelixWaweru** [comment]
Hi @kelvin-zhao 

If you're sending the API response, one option could be to use the `textToSpeechStream`  function and then stream the response to the client. The client can then convert the received stream into an audio file.

**Comment by FelixWaweru** [comment]
Hi @kelvin-zhao
Did this approach work for you?

**Comment by kelvin-zhao** [comment]
Hi @FelixWaweru,
Thanks for checking-in! Ah, in the end I didn't go ahead with this approach and tried to transfer the initial buffer given by the elevenlabs back through to the front end. I will loop back and try this package again on my next run!
