### ISSUE TITLE
Add please function for GET /v1/models

### ISSUE THREAD

**Issue by AEiosApp** [FelixWaweru/elevenlabs-node#29]
Simple feature request, to add function for GET /v1/models request
https://docs.elevenlabs.io/api-reference/models-get

**Comment by FelixWaweru** [comment]
Thanks for the suggestion @AEiosApp 

This feature is now available in the latest release
https://github.com/FelixWaweru/elevenlabs-node/releases/tag/elevenlabs-node%401.2.0
