### ISSUE TITLE
ElevenLabs V2

### ISSUE THREAD

**Issue by antheiz** [FelixWaweru/elevenlabs-node#32]
EvelevenLabs V2 has been release yesterday: https://github.com/elevenlabs/elevenlabs-python/releases/tag/v0.2.26

Thank you in advance!

**Comment by FelixWaweru** [comment]
Thanks for sharing this update @antheiz 

You can now use the ElevenLabs V2 Model in the TTS functions using the `modelId` [variable](https://github.com/FelixWaweru/elevenlabs-node#parameters).
