### ISSUE TITLE
Speaking the other languages

### ISSUE THREAD

**Issue by TiagoGouvea** [FelixWaweru/elevenlabs-node#37]
**Describe the bug**
I read on Eleventlabs docs that Portuguese is one of the supported languages, and I'm trying to make it speak in Brazilian Portuguese, but I can't.

In fact, I didn't find where to say `language:pt-BR` or something like that. I just sent a Brazilian written text.

But the result is some like an American trying to read in Portuguese, it's annoying. 😅 

**Expected behavior**
To ask `voice.textToSpeechStream` with the desired language as a parameter.

. . .

Could you guys help me make it work?

**Comment by milkmanjr** [comment]
Oi! @TiagoGouvea

Portuguese works for me when I change the modelID to eleven_multilingual_v2 with the text in Portuguese.

**Comment by FelixWaweru** [comment]
> Oi! @TiagoGouvea
> 
> Portuguese works for me when I change the modelID to eleven_multilingual_v2 with the text in Portuguese.

This is correct

@TiagoGouvea  You can also check the V2 [docs](https://github.com/FelixWaweru/elevenlabs-node#features) to reference different [variables](https://github.com/FelixWaweru/elevenlabs-node#parameters) you can pass.
