### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Juan-Fruto** [FelixWaweru/elevenlabs-node#44]
How can i switch the language?

I don´t know if it is possible because also I coudn´t find that option in the oficial api documentation.

**Comment by FelixWaweru** [comment]
Hi @Juan-Fruto 

You can use `elevenlabs_multilingual_v2` to use different languages. To do so, you can pass `elevenlabs_multilingual_v2` to the `modeId` variable like so:

```javascript
voice.textToSpeech({

    fileName:        "audio.mp3",                    // The name of your audio file
    textInput:       "Esto es español",             // The text you wish to convert to speech
    modelId:         "elevenlabs_multilingual_v2",   // The ElevenLabs Model ID

  }).then((res) => {
    console.log(res);
});
```

Docs: https://elevenlabs.io/docs/speech-synthesis/models#multilingual-v2
